# Light/dark theme for the Hermes desktop app.
#
# Hermes has three surfaces and only two theming units:
#
#   * A SKIN (`$HERMES_HOME/skins/*.yaml`, ./hermes-agent-skin.nix) is what
#     the CLI and TUI read, and it is single-mode by contract. The desktop's
#     converter says so outright: "A skin is single-mode, so both `colors` and
#     `darkColors` get the converted palette" (apps/desktop/src/themes/skin.ts),
#     and the skin name is only read from config.yaml at startup, with no env
#     override. So a skin can never answer the desktop's light/dark switch.
#
#   * A DesktopTheme carries a real pair -- `colors` is the light palette and
#     `darkColors` the dark one (apps/desktop/src/themes/types.ts) -- which is
#     exactly what Appearance ▸ light/dark/system chooses between. `system`
#     resolves through prefers-color-scheme, which Electron answers from the
#     appearance portal, the same signal noctalia writes on a mode toggle.
#
# A desktop plugin can contribute a DesktopTheme as a data contribution to the
# `themes` registry area (apps/desktop/src/themes/user-themes.ts), and runtime
# plugins are scanned from `<HERMES_HOME>/desktop-plugins/<name>/plugin.js` and
# hot-reloaded, so nix can write one. That is what this module does.
#
# The skin stays as it is: it still themes the CLI and TUI, and still gives the
# desktop a converted entry. This adds the one thing a skin cannot express.
{
  config,
  lib,
  pkgs,
  inputs,
  ...
}:
let
  hermesCfg = config.services.hermes-agent;
  skinCfg = config.theming.hermes-agent;

  schemes = import ./schemes.nix { inherit pkgs inputs; };
  darkColors = schemes.dark.withHashtag;
  lightColors = schemes.light.withHashtag;
  fonts = import ./font.nix;

  themeName = "base16-auto";

  # base16 -> DesktopThemeColors. Written once and applied to both schemes so
  # the two halves cannot drift; only the input palette differs.
  #
  # The accent follows theming.hermes-agent.accentColor's reasoning rather than
  # its value: that option is a single hex resolved from the dark scheme, and
  # reusing it here would paint the dark accent onto the light palette. Both
  # take the same SLOT instead, which noctalia.nix points at base07 (lavender)
  # in either scheme.
  mkColors =
    c:
    let
      accent = c.base07;
    in
    {
      background = c.base00;
      foreground = c.base05;

      card = c.base01;
      cardForeground = c.base05;
      popover = c.base01;
      popoverForeground = c.base05;

      muted = c.base02;
      mutedForeground = c.base04;

      primary = accent;
      primaryForeground = c.base00;
      secondary = c.base02;
      secondaryForeground = c.base05;
      accent = c.base0C;
      accentForeground = c.base00;

      border = c.base02;
      input = c.base02;
      ring = accent;
      midground = accent;
      composerRing = accent;

      destructive = c.base08;
      destructiveForeground = c.base00;

      sidebarBackground = c.base01;
      sidebarBorder = c.base02;
      userBubble = c.base02;
      userBubbleBorder = c.base03;
    };

  # The integrated terminal's ANSI palette, mapped exactly as the noctalia and
  # ghostty terminal blocks are, so all three agree.
  mkTerminal = c: {
    foreground = c.base05;
    cursor = c.base07;
    selectionBackground = c.base02;

    black = c.base00;
    red = c.base08;
    green = c.base0B;
    yellow = c.base0A;
    blue = c.base0D;
    magenta = c.base0E;
    cyan = c.base0C;
    white = c.base05;

    brightBlack = c.base03;
    brightRed = c.base08;
    brightGreen = c.base0B;
    brightYellow = c.base0A;
    brightBlue = c.base0D;
    brightMagenta = c.base0E;
    brightCyan = c.base0C;
    brightWhite = c.base07;
  };

  theme = {
    name = themeName;
    label = "Stylix Auto";
    description = "Generated from the active base16 schemes";

    # colors is the LIGHT half and darkColors the dark one -- not a typo. See
    # the DesktopTheme doc comments: "Light palette (also reused for dark when
    # darkColors is omitted)" / "Hand-tuned dark palette".
    colors = mkColors lightColors;
    darkColors = mkColors darkColors;
    terminal = mkTerminal lightColors;
    darkTerminal = mkTerminal darkColors;

    typography = {
      fontSans = fonts.propo;
      fontMono = fonts.mono;
    };
  };

  # A runtime plugin is an ES module default-exporting { id, register }, and may
  # import nothing but @hermes/plugin-sdk and react (unsupportedImports() in
  # contrib/runtime-loader.ts rejects anything else). This one imports neither:
  # a data contribution is a plain object, so the module stays dependency-free.
  pluginJs = pkgs.writeText "hermes-base16-auto-plugin.js" ''
    // Generated by home-manager (home-manager/hermes-desktop-theme.nix).
    // Contributes one DesktopTheme carrying both palettes, so the app's
    // light/dark/system switch has something to switch between.

    const theme = ${builtins.toJSON theme}

    export default {
      id: 'base16-auto-theme',
      name: 'Stylix Auto Theme',
      description: 'Light/dark desktop palette generated from the base16 schemes.',
      register(ctx) {
        ctx.register({ id: 'theme', area: 'themes', data: theme })
      }
    }
  '';
in
{
  config = lib.mkIf (skinCfg.enable && hermesCfg.enable) {
    # Same home.file reasoning as the skin in ./hermes-agent-skin.nix: the
    # plugin is pure derived data with no runtime writer, and hermesHome is
    # asserted to live under the home directory by that module.
    home.file."${lib.removePrefix "${config.home.homeDirectory}/" hermesCfg.hermesHome}/desktop-plugins/base16-auto/plugin.js" =
      {
        source = pluginJs;
      };
  };
}
